PEBC implementation
flexiblepower/s2-python pull request #60
Opened 2024-12-26 08:25 UTC by VladIftime

This pull request introduces several new classes and updates existing ones in the `src/s2python/pebc` directory. These changes primarily involve importing necessary modules, defining new classes, and configuring model validation. The most important changes include the addition of new classes for handling PEBC constraints and envelopes, as well as updating model configurations to enable assignment validation.

2025-01-07 16:31 UTC, jorritn commented
This will resolve #64

2025-01-09 15:09 UTC, wcoenraads requested changes
Thanks for implementing this! Your changes look good to me; however, the control type still needs to be added to `s2python/s2_control_types.py`. If you add that, I think we can merge this.

P.S. I sent you an email with an extra question I had regarding the generated code.

2025-01-13 10:05 UTC, VladIftime commented
> Thanks for implementing this! Your changes look good to me; however, the control type still needs to be added to `s2python/s2_control_type.py`. If you add that, I think we can merge this.
> 
> P.S. I sent you an email with an extra question I had regarding the generated code.

I did not receive any emails.

2025-01-13 12:10 UTC, wcoenraads requested changes
Thanks for adding PEBC to `s2_control_type.py`! However, it seems this commit also includes a bunch of build files in `build/`. If you remove those, we're good to merge.

2025-01-14 15:21 UTC, wcoenraads commented
Another minor issue I discovered while working on a PEBC example: `PEBCInstruction` is missing from `pebc/__init__.py`.

2025-01-22 10:49 UTC, wcoenraads commented
Thanks for adding the missing classes! I think the only two things remaining are:
- Adding `PEBCInstruction` to the exports in `__init__.py`
- Removing the build files from the pull request

Once that's done, this is ready to merge.

2025-02-10 14:58 UTC, wcoenraads approved these changes
Looks good to me - thanks!

2025-03-03 09:24 UTC, merged